import type { Metadata } from "next";
import "./globals.css";
import { TodoProvider } from "@/context/TodoContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <TodoProvider>{children}</TodoProvider>
      </body>
    </html>
  );
}
